export const placeholderThings = [
  'nail guitar solo',
  'graph churn rate',
  'revamp about page',
  'practice handstands',
  'authentication logic',
  'interview prep',
  'record podcast',
  'record narration',
  'edit video',
  'submit pitch',
  'work the socials',
  'chase Alison',
  'meditation',
  'stock up kitchen for dinner',
  'finalize guest-list',
  'automate end-of-day report',
  'tune flux capacitor',
]
